In [102]:
import pandas as pd
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
df = pd.read_csv(url, header = None)

Aqui ponemos a ejecutar el primer codigo para que sea con el que iremos trabajando en los siguientes puntos.

In [103]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

Pequeño ejemplo de como se verian los datos solo tomando las primeras 10 columnas.

In [104]:
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Del mismo modo, pero con las 10 primeras filas.

In [105]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
print("headers\n", headers)

headers
 ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

La tabla aparece con numeros en los titulos de los valores, para cambiar esto debemos crear una lista con los encabezados que queremos que tenga.

In [106]:
df.columns = headers
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

Aqui lo que buscamos es que al reemplazar la columnas que tenian por titulos los anteriores numeros, nos de una mejor vista de lo que queremos interpretar.

In [107]:
ruta = 'D:\CDP\Senatec\Analisis de Datos/automobile.csv'
df.to_csv(ruta)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Germa\AppData\Local\Temp\ipykernel_10432\2311564838.py:1: SyntaxWarning: invalid escape sequence '\C'
  ruta = 'D:\CDP\Senatec\Analisis de Datos/automobile.csv'

Aqui guardamos la tabla hasta el momento con los nombres en las columnas cambiados.

In [108]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

Se usa el df.dtype para saber con que tipo de datos se esta trabajando, Nota mental, cuando se inicie analisis, recordar siempre volver a correr todo el codigo.

In [109]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

Funcion para describir en esencia lo analitico de los datos.

In [110]:
df.describe(include='all')

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205,205,205,205,205,205,205,205,205.000000,...,205.000000,205,205,205,205.000000,205,205,205.000000,205.000000,205
unique,NaN,52,22,2,2,3,5,3,2,NaN,...,NaN,8,39,37,NaN,60,24,NaN,NaN,187
top,NaN,?,toyota,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,?
freq,NaN,41,32,185,168,114,96,120,202,NaN,...,NaN,94,23,20,NaN,19,37,NaN,NaN,4
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,...,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,...,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

Con este argumento df.desccribe(include='All) se busca incluir al analisis no solo los datos numericos sino tambien los demas objetos, asi salen nuevos parametros como lo son: unique = que son valores unicos o que aparecen pocas veces en los datos, top = que son los que mas aparecen y freq = que son el numero de veces que aparecen los top.

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

Ofrece un resumen conciso del marco de datos.

# Inicio del modulo 2.
En este modulo se trataran los siguientes temas:
Limpieza o preprocesamiento de los datos.
Identificacion de espacios vacios.
Formato de los datos.
Normalizacion de datos.
Agrupamiento de datos.
Variables categoricas.

In [112]:
df['symboling']=df['symboling']+1

Aqui hacemos un manejo de partes puntuales de los datos.

In [113]:
df.dropna()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,4,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,3,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,3,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,0,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,0,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,0,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,0,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Usamos df.dropna() para eliminar los datos marcados como N/A en el df.

In [114]:
df.dropna(subset=['price'], axis=0, inplace= True)
df = df.dropna(subset=['price'], axis=0)

Usamos df.dropna(subset=['price'], axis=0) para hacer la correcta eliminacion de filas en especifico, en este caso, las filas donde no halla valor en precio, para mejorar el analisis sin cambiar el marco de datos como lo hace df.dropna(subset=['price'], axis=0, inplace= True).

In [115]:
df['normalized-losses'] = pd.to_numeric(df['normalized-losses'], errors='coerce')
mean = df['normalized-losses'].mean()
df['normalized-losses'].replace(np.nan, mean)

0      122.0
1      122.0
2      122.0
3      164.0
4      164.0
       ...
200     95.0
201     95.0
202     95.0
203     95.0
204     95.0
Name: normalized-losses, Length: 205, dtype: float64

En esta parte, hacemos una limpieza de los codigos con lo siguientes ejemplos, primero nos aparecia un error porque a la hora de sacar la media para reemplazar en los valores N/A no nos dejava, esto se soluciono con el codigo df['normalized-losses'] = pd.to_numeric(df['normalized-losses'], errors='coerce') que tiene como funcion, transformar los datos en la columna en numericos, porque se piensa que los datos aun estando en numeros aparecen con otro tipo, despues se le saca la media a los datos con mean = df['normalized-losses'].mean() y se reemplaza con la media en los valores N/A con el siguiente codigo df['normalized-losses'].replace(np.nan, mean), en esto se vio el manejo de replace como erramienta para reemplazar datos faltantes o nulos.

In [116]:
df['city-mpg'] = 235 / df['city-mpg']
df.rename(columns={'city-mpg': 'city-L/100km'}, inplace=True)
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-mpg,price
0,4,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,13495
1,4,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
2,2,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
3,3,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
4,3,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
5,3,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250
6,2,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,17710
7,2,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,18920
8,2,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,13.823529,20,23875
9,1,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,14.687500,22,?

En el anterior codigo, lo que hacemos es cambiar la unidades de una variable y renombrando la columna para que se sepa que se cambiaron las unidades, esto se hace para mejorar el analisis dependiendo de los tipos de datos que se usan, esta parte corresponden al Formateo de datos.

In [117]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['price'] = df['price'].fillna(0).astype(int)
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-L/100km         float64
highway-mpg            int64
price                  int64
dtype: object

Con lo anterior, transformamos todos lo valores en numericos con la funcion df['price'] = pd.to_numeric(df['price'], errors='coerce') que ya habiamos visto, despues los valores N/A los reemplazamos por ceros y los convierte en int.

In [118]:
df['length'] = df['length'] / df['length'].max()
df['length']

0      0.811148
1      0.811148
2      0.822681
3      0.848630
4      0.848630
         ...
200    0.907256
201    0.907256
202    0.907256
203    0.907256
204    0.907256
Name: length, Length: 205, dtype: float64

Con la normalizacion de los datos, lo que se busca es que las escalas de esta para los analisis posteriores tenga sentido, en el ejemplo anterior, los valores con los que se compara la columna length divieren mucho con otras, esto a medida que se hacen mas procedimientos como regresiones lineales y demas puede afectar el modelo predictivo, por ende con el codigo df['length'] = df['length'] / df['length'].max() dividimos cada valor de length por el valor mas alto de esa misma columna, esto se denomina ESCALADO DE CARACTERISTICAS SIMPLE.

In [119]:
df['length'] = (df['length'] - df['length'].min()) / (df['length'].max() - df['length'].min())
df['length']

0      0.413433
1      0.413433
2      0.449254
3      0.529851
4      0.529851
         ...
200    0.711940
201    0.711940
202    0.711940
203    0.711940
204    0.711940
Name: length, Length: 205, dtype: float64

Con el metodo MINIMO Y MAXIMO hacemos de igual forma una normalizacion pero en este caso restamos cada valor por el valor minimo de esa columna, despues dividimos el resultado por la resta del valor maximo con el valor minimo, al igual que en el anterior ejemplo, los valores bajan de escala.

In [120]:
df['length'] = (df['length'] - df['length'].mean()) / df['length'].std()
df['length']

0     -0.425480
1     -0.425480
2     -0.230948
3      0.206750
4      0.206750
         ...
200    1.195622
201    1.195622
202    1.195622
203    1.195622
204    1.195622
Name: length, Length: 205, dtype: float64

El metodo Z-SCORE lo que hace es que los valores de length los multiplica por el promedio de los valores de la columna y lo divide por la desviacion estandar de esta, al igual que con los anteriores metodos, se pueden tener datos de menor escala ya que estos pueden ir desde -3 a 3.

In [121]:
interv = np.linspace(min(df['price']), max(df['price']), 4)
group_names = ['Low', 'Medium', 'High']
df['price_category'] = pd.cut(df['price'], bins=interv, labels=group_names, include_lowest=True)
df['price_category']

0         Low
1      Medium
2      Medium
3         Low
4      Medium
        ...
200    Medium
201    Medium
202    Medium
203    Medium
204    Medium
Name: price_category, Length: 205, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

En este ejercicio usamos el BINNING que es la agrupacion de valores para mejorar el modelo predictivo y de toma de desiciones segun los datos, asi mismo se utilizo el codigo interv = np.linspace(min(df['price']), max(df['price']), 4) para dividir los valores en 'price' en 3 categorias, esto lo que hace es tomar el valor minimo y maximo y dividir desde ese punto los demas valores en bajo, medio o alto bajo cierto intervalo equivalente. Asi mismo se definieron las etiquetas descriptivas para cada intervalo con el codigo group_names = ['Low', 'Medium', 'High'] teniendo en cuenta la agrupacion anterior. Con el codigo df['price_category'] = pd.cut(df['price'], bins=interv, labels=group_names, include_lowest=True) se hacen varias cosas al mismo tiempo, primero se crea una nueva columna ['price_category'], se categoriza los valores de 'price' en intervalos para la nueva columna con pd.cut(df['price']. Se definen los limites de los intervalos a los que los valores seran agrupados con  'interv' al parametro bins con bins=interv. Por ultimo se incluye en la agrupacion al valor mas pequeño que seria con el que comenzaria el intervalo como tal con include_lowest=True). Junto esto forman una agrupacion que hace posible una mejor interpretacion de los datos optenidos.

In [122]:
dummies = pd.get_dummies(df['fuel-type'], prefix='fuel-type').astype(int)
df = pd.concat([df, dummies], axis=1)
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-mpg,price,price_category,fuel-type_diesel,fuel-type_gas
0,4,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,11.190476,27,13495,Low,0,1
1,4,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,11.190476,27,16500,Medium,0,1
2,2,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154,5000,12.368421,26,16500,Medium,0,1
3,3,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,3.40,10.0,102,5500,9.791667,30,13950,Low,0,1
4,3,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,3.40,8.0,115,5500,13.055556,22,17450,Medium,0,1
5,3,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.40,8.5,110,5500,12.368421,25,15250,Medium,0,1
6,2,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,3.40,8.5,110,5500,12.368421,25,17710,Medium,0,1
7,2,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,3.40,8.5,110,5500,12.368421,25,18920,Medium,0,1
8,2,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.40,8.3,140,5500,13.823529,20,23875,Medium,0,1
9,1,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,3.40,7.0,160,5500,14.687500,22,0,Low,0,1

CONVERCION DE UNA VARIABLE CATEGORICA EN VARIABLE CUANTITATIVA. En esta parte de busca la cuantificacion de los valores en la columna de tipo de combustible, para esto, tenemos el siguiente codigo dummies = pd.get_dummies(df['fuel-type'], prefix='fuel-type').astype(int) donde creamos dos nuevas columnas llamadas 'tipo de combustible Gas' y 'tipo de combustible Diesel' a esto le agregamos el codigo astype(int) para modificar los valores a numerico ya que cuando aparecias sin esa parte, se mostraba un valor booleano. Seguido a eso concatenamos las dos nuevas columnas con el codigo df = pd.concat([df, dummies], axis=1) para que esta hiciera parte de los datos en si.